spring:
  application:
    name: Teacher_portal

  server:
    port: 8080

  kafka:
    bootstrap-servers: pkc-l7pr2.ap-south-1.aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      group-id: daily-reminder-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.Teacher_portal.Entity;

    properties:
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='N2ZSV7IUR3HVWV3Q' password='1KmOlGj/lW8KQzgSlR0H9HfUYNyKd2BtWUnDM62/VsuigwcD/ce4Jq/UK5c0y0py';
      security:
        protocol: SASL_SSL
      session:
        timeout:
          ms: 45000

  client:
    id: ccloud-springboot-client-d8e32765-5aeb-4dcd-abf8-f89de2e78d2b


  security:
    oauth2:
      client:
        registration:
          zoom:
            client-id: MGaqEQN9SYmctFcSGNvAZg
            client-secret: DRAQF3ORlPaBUHoJsn3BLJLrWFiyox9Y
            scope: read,write,openid
            authorization-grant-type: authorization_code
            redirect-uri: https://api.zoom/classroom
        provider:
          zoom:
            authorization-uri: https://zoom.us/oauth/authorize
            token-uri: https://zoom.us/oauth/token
            user-info-uri: https://api.zoom.us/v2/users/me
            user-name-attribute: id

  jpa:
    hibernate:
      ddl-auto: update
    # show-sql: true
    # properties:
    #   hibernate:
    #     format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/stportal
    username: root
    password: MySQL@2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: karma.rohit026@gmail.com
    # password: terc pvdi yptv oznt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework: DEBUG
    # org.springframework.security: DEBUG

# Uncomment the following for case-insensitive enums (if required)
# spring:
#   jackson:
#     enumeration:
#       case-insensitive: true
